### ISSUE TITLE
Does not work on Firefox 114

### ISSUE THREAD

**Issue by bugnano** [BiagioFesta/wtransport#17]
So, I used the latest git of wtransport, and built both the server and client examples.
For the server I generated the certificates with mkcert, and modified the server example code to point to the generated certificates.
If I run the server and client examples, everything works.
But if I try the server example, and on the client I use Firefox 114, and go to

https://webtransport.day/

and pass
```
https://[::1]:4433/
```

as the URL and click connect, the connection fails, and the server crashes with the error:

```
Waiting for incoming connection...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionClosed(ConnectionClose(ConnectionClose { error_code: Code::crypto(2a), frame_type: None, reason: b"" }))', wtransport/examples/server.rs:22:63
stack backtrace:
   0:     0x559fa52a0dda - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3fd184b2101eb13c
   1:     0x559fa52c421f - core::fmt::write::h51fa8e21bfac13ae
   2:     0x559fa529e045 - std::io::Write::write_fmt::hb170cc94d5e2f613
   3:     0x559fa52a0ba5 - std::sys_common::backtrace::print::h403826a4179d5670
   4:     0x559fa52a224e - std::panicking::default_hook::{{closure}}::ha8e7f4094a32fcab
   5:     0x559fa52a1ff5 - std::panicking::default_hook::hc86b583b1c4ca7a5
   6:     0x559fa52a27ae - std::panicking::rust_panic_with_hook::hc497c7954fcfd668
   7:     0x559fa52a26a9 - std::panicking::begin_panic_handler::{{closure}}::h7188665de380b804
   8:     0x559fa52a1246 - std::sys_common::backtrace::__rust_end_short_backtrace::hb744ac52f62fb536
   9:     0x559fa52a2402 - rust_begin_unwind
  10:     0x559fa4dd4d43 - core::panicking::panic_fmt::h5fbbc72c7fa660e4
  11:     0x559fa4dd52e3 - core::result::unwrap_failed::h86096f7f4e455f48
  12:     0x559fa4dd781e - core::result::Result<T,E>::unwrap::h127d240e5dbce379
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/core/src/result.rs:1089:23
  13:     0x559fa4de171d - server::main::{{closure}}::h81fef686e2798d64
                               at /robba/tmp/wtransport/wtransport/examples/server.rs:22:26
  14:     0x559fa4ddfe14 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h8e76271b240a8e96
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:63
  15:     0x559fa4ddfc40 - tokio::runtime::coop::with_budget::h5c4ee202f8c92a52
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  16:     0x559fa4ddfc40 - tokio::runtime::coop::budget::hdc06251f8845cd48
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  17:     0x559fa4ddfc40 - tokio::runtime::park::CachedParkThread::block_on::h9a64a77b1cd98e90
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:31
  18:     0x559fa4de3693 - tokio::runtime::context::BlockingRegionGuard::block_on::h55ee2199d53c0cbb
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/context.rs:315:13
  19:     0x559fa4ddc7b1 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h16d0d92c0637faa8
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/mod.rs:66:9
  20:     0x559fa4de6278 - tokio::runtime::runtime::Runtime::block_on::ha769ab0ab12ced3c
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/runtime.rs:304:45
  21:     0x559fa4ddbf7b - server::main::hdb4f40228dcfe0ac
                               at /robba/tmp/wtransport/wtransport/examples/server.rs:20:5
  22:     0x559fa4ddcd5b - core::ops::function::FnOnce::call_once::h7a44d2145209746b
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/core/src/ops/function.rs:250:5
  23:     0x559fa4de0c3e - std::sys_common::backtrace::__rust_begin_short_backtrace::h4be0ad8be2eb05ee
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/std/src/sys_common/backtrace.rs:134:18
  24:     0x559fa4dda901 - std::rt::lang_start::{{closure}}::h587d1736801f902c
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/std/src/rt.rs:166:18
  25:     0x559fa529a60e - std::rt::lang_start_internal::h8471d15dead791e4
  26:     0x559fa4dda8da - std::rt::lang_start::h3942d2b55594a650
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/std/src/rt.rs:165:17
  27:     0x559fa4ddc02e - main
  28:     0x7f7fae884b4a - __libc_start_call_main
  29:     0x7f7fae884c0b - __libc_start_main@@GLIBC_2.34
  30:     0x559fa4dd54c5 - _start
  31:                0x0 - <unknown>
```

Could it be that Firefox 114 uses a different version of the protocol?

**Comment by BiagioFesta** [comment]
This is not really a crash of the library, but rather `example/server.rs` that does not handle error handling as it performs `.unwrap()` on `Result`s (being a demonstrative example).

---

The server was not able to accept the connection because the client (Firefox) aborts the connection during handshake (connection initialization).

If you look at the `Err` reported by the `Connection` action:
```
`Err` value: ConnectionClosed(ConnectionClose(ConnectionClose { error_code: Code::crypto(2a), frame_type: None, reason: b"" }))'
```

The client (Firefox) is aborting the connection returning `0x2a` error code (it means `BAD_CERTIFICATE`).

Thus, Firefox does not accept the self-signed certificate generated with the `gencert`.

---

If you see on [README.md](https://github.com/BiagioFesta/wtransport/blob/master/README.md), when using self-signed certificate with google-chrome, one needs to specify an exception for that certificate. In particular, `--origin-to-force-quic-on=localhost:4433` and `--ignore-certificate-errors-spki-list=FINGERPRINT`.

I suspect something similar must be done with Firefox. 

However, I am not aware of any Firefox mechanisms in order to allow self-signed local certificates in a similar manner.

---

I am going to close this ticket in the next few days, if nothing else pops out.

However, feel free to update this ticket if you find a solution for self-signed certificate on Firefox, so maybe we can update the README.md

**Comment by bugnano** [comment]
So there was the issue that I'm using [mkcert](https://github.com/FiloSottile/mkcert), which installs a new CA, so that I don't need self-signed certificates, or a fingerprint to whitelist.
The problem is that I'm using the Flatpak version of Firefox, and the upstream mkcert didn't install the CA for Firefox on Flatpak.
I then compiled from source the mkcert code with this patch https://github.com/FiloSottile/mkcert/pull/499 that installs the CA on the Firefox Flatpak as well.

When I run the wtransport server and connect from Firefox, now the server crashes with a different error:

```
Waiting for incoming connection...
Waiting for data from client...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ApplicationClosed(ApplicationClose { code: 256, reason: [] })', wtransport/examples/server.rs:51:39
stack backtrace:
   0:     0x564d9ca28e1a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3fd184b2101eb13c
   1:     0x564d9ca4c25f - core::fmt::write::h51fa8e21bfac13ae
   2:     0x564d9ca26085 - std::io::Write::write_fmt::hb170cc94d5e2f613
   3:     0x564d9ca28be5 - std::sys_common::backtrace::print::h403826a4179d5670
   4:     0x564d9ca2a28e - std::panicking::default_hook::{{closure}}::ha8e7f4094a32fcab
   5:     0x564d9ca2a035 - std::panicking::default_hook::hc86b583b1c4ca7a5
   6:     0x564d9ca2a7ee - std::panicking::rust_panic_with_hook::hc497c7954fcfd668
   7:     0x564d9ca2a6e9 - std::panicking::begin_panic_handler::{{closure}}::h7188665de380b804
   8:     0x564d9ca29286 - std::sys_common::backtrace::__rust_end_short_backtrace::hb744ac52f62fb536
   9:     0x564d9ca2a442 - rust_begin_unwind
  10:     0x564d9c55cd43 - core::panicking::panic_fmt::h5fbbc72c7fa660e4
  11:     0x564d9c55d2e3 - core::result::unwrap_failed::h86096f7f4e455f48
  12:     0x564d9c55f73d - core::result::Result<T,E>::unwrap::h078960c0a3bf55cc
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/core/src/result.rs:1089:23
  13:     0x564d9c569dcd - server::main::{{closure}}::h81fef686e2798d64
                               at /robba/tmp/wtransport/wtransport/examples/server.rs:51:33
  14:     0x564d9c567e44 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h8e76271b240a8e96
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:63
  15:     0x564d9c567c70 - tokio::runtime::coop::with_budget::h5c4ee202f8c92a52
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  16:     0x564d9c567c70 - tokio::runtime::coop::budget::hdc06251f8845cd48
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  17:     0x564d9c567c70 - tokio::runtime::park::CachedParkThread::block_on::h9a64a77b1cd98e90
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:31
  18:     0x564d9c56b6b3 - tokio::runtime::context::BlockingRegionGuard::block_on::h55ee2199d53c0cbb
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/context.rs:315:13
  19:     0x564d9c5647b1 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h16d0d92c0637faa8
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/mod.rs:66:9
  20:     0x564d9c56e2b8 - tokio::runtime::runtime::Runtime::block_on::ha769ab0ab12ced3c
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/runtime.rs:304:45
  21:     0x564d9c563f7b - server::main::hdb4f40228dcfe0ac
                               at /robba/tmp/wtransport/wtransport/examples/server.rs:20:5
  22:     0x564d9c564d5b - core::ops::function::FnOnce::call_once::h7a44d2145209746b
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/core/src/ops/function.rs:250:5
  23:     0x564d9c568c6e - std::sys_common::backtrace::__rust_begin_short_backtrace::h4be0ad8be2eb05ee
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/std/src/sys_common/backtrace.rs:134:18
  24:     0x564d9c562901 - std::rt::lang_start::{{closure}}::h587d1736801f902c
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/std/src/rt.rs:166:18
  25:     0x564d9ca2264e - std::rt::lang_start_internal::h8471d15dead791e4
  26:     0x564d9c5628da - std::rt::lang_start::h3942d2b55594a650
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/std/src/rt.rs:165:17
  27:     0x564d9c56402e - main
  28:     0x7f5bef1f1b4a - __libc_start_call_main
  29:     0x7f5bef1f1c0b - __libc_start_main@@GLIBC_2.34
  30:     0x564d9c55d4c5 - _start
  31:                0x0 - <unknown>
```

**Comment by BiagioFesta** [comment]
Thank you for the context.

> Could it be that Firefox 114 uses a different version of the protocol?

I think you might be right then.

Testing on my side, the error might be due to the server WebTransport session response. In particular, [this field](https://github.com/BiagioFesta/wtransport/blob/193b7f2137e98bb09397b13965052d370ca319c1/wtransport/src/driver/response.rs#L13).

```
sec-webtransport-http3-draft", "draft02"
```

That is not really "standard" and comes out because Google chrome requires it.

WebTransport is still a draft, so I expect there might be some miss-alignments between Chrome and Firefox implementations.

Could you please try to remove that line and check if that solves your case?

**Comment by BiagioFesta** [comment]
New version (`0.1.2`) now should care about headers response.
So both firefox and chrome are automatically supported

**Comment by bugnano** [comment]
Version 0.1.2 still doesn't work on Firefox 114.

This is the server output if I try toconnect from Firefox:

```
Waiting for incoming connection...
Incoming request
 Authority: localhost:4433
 Path: /
Waiting for data from client...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ApplicationClosed(ApplicationClose { code: 256, reason: [] })', wtransport/examples/server.rs:39:45
stack backtrace:
   0:     0x557876f989aa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3fd184b2101eb13c
   1:     0x557876fbbdef - core::fmt::write::h51fa8e21bfac13ae
   2:     0x557876f95c15 - std::io::Write::write_fmt::hb170cc94d5e2f613
   3:     0x557876f98775 - std::sys_common::backtrace::print::h403826a4179d5670
   4:     0x557876f99e1e - std::panicking::default_hook::{{closure}}::ha8e7f4094a32fcab
   5:     0x557876f99bc5 - std::panicking::default_hook::hc86b583b1c4ca7a5
   6:     0x557876f9a37e - std::panicking::rust_panic_with_hook::hc497c7954fcfd668
   7:     0x557876f9a279 - std::panicking::begin_panic_handler::{{closure}}::h7188665de380b804
   8:     0x557876f98e16 - std::sys_common::backtrace::__rust_end_short_backtrace::hb744ac52f62fb536
   9:     0x557876f99fd2 - rust_begin_unwind
  10:     0x557876ae2d43 - core::panicking::panic_fmt::h5fbbc72c7fa660e4
  11:     0x557876ae32e3 - core::result::unwrap_failed::h86096f7f4e455f48
  12:     0x557876af4fc8 - core::result::Result<T,E>::unwrap::he8be9c8377458d53
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/core/src/result.rs:1089:23
  13:     0x557876af2be4 - server::main::{{closure}}::h1f1d4cfa85f09155
                               at /robba/tmp/wtransport-master/wtransport/examples/server.rs:39:38
  14:     0x557876ae7a84 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h887df42f1b3127dc
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.0/src/runtime/park.rs:283:63
  15:     0x557876ae744a - tokio::runtime::coop::with_budget::hd04ae9096b68a29d
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.0/src/runtime/coop.rs:107:5
  16:     0x557876ae744a - tokio::runtime::coop::budget::h42602ebdf21a22c8
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.0/src/runtime/coop.rs:73:5
  17:     0x557876ae744a - tokio::runtime::park::CachedParkThread::block_on::h43dd752ba90a791a
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.0/src/runtime/park.rs:283:31
  18:     0x557876ae4381 - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::haf99e7a7647de8fd
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.0/src/runtime/context/blocking.rs:66:9
  19:     0x557876ae4666 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h25fffb6fc704e586
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  20:     0x557876ae38ea - tokio::runtime::context::runtime::enter_runtime::h2be66829630aa94d
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.0/src/runtime/context/runtime.rs:65:16
  21:     0x557876ae4601 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h0e83e5b9bf19703b
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  22:     0x557876af5d18 - tokio::runtime::runtime::Runtime::block_on::h2c3e7a88eb21870a
                               at /home/fri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.0/src/runtime/runtime.rs:313:45
  23:     0x557876afa0cd - server::main::h1b7eedda12affba1
                               at /robba/tmp/wtransport-master/wtransport/examples/server.rs:20:5
  24:     0x557876ae8e0b - core::ops::function::FnOnce::call_once::hbe04b82509e0d2fb
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/core/src/ops/function.rs:250:5
  25:     0x557876af629e - std::sys_common::backtrace::__rust_begin_short_backtrace::h60f779d1f56f6033
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/std/src/sys_common/backtrace.rs:134:18
  26:     0x557876ae6cd1 - std::rt::lang_start::{{closure}}::h60fcb6325d972857
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/std/src/rt.rs:166:18
  27:     0x557876f921de - std::rt::lang_start_internal::h8471d15dead791e4
  28:     0x557876ae6caa - std::rt::lang_start::h553731e93ee33e47
                               at /builddir/build/BUILD/rustc-1.70.0-src/library/std/src/rt.rs:165:17
  29:     0x557876afa17e - main
  30:     0x7f8d785ebb4a - __libc_start_call_main
  31:     0x7f8d785ebc0b - __libc_start_main@@GLIBC_2.34
  32:     0x557876ae34c5 - _start
  33:                0x0 - <unknown>
```

**Comment by BiagioFesta** [comment]
Now it should be fixed in `master`

**Comment by bugnano** [comment]
I confirm that the latest master works on Firefox.
Thank you very much😀
